# 缩进表示上下级
# 左对齐表示同等级
# #表示注释
# 值与冒号之间必须有空格
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_26
server:
  servlet:
    context-path: /
  port: 8081

  # 初始化一个Student aqw
  student:
        sid: 1001
        sname: tom
        sage: 19
        enjoy:
            - lq
            - zq
            - pq
        parentName: {mather: hmm,father: lijun}
        dog:
              dage: 1
              dname: 大黄
              dsex: 母
              date: "2020-10-11 12:13:14"